# Generated by Django 3.0.6 on 2020-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecrime', '0005_auto_20200517_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcase',
            name='case_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
