# Generated by Django 3.0.6 on 2020-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecrime', '0008_auto_20200519_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcase',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
