# Generated by Django 3.0.6 on 2020-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecrime', '0009_auto_20200519_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCriminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='Male', max_length=1)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
