# Generated by Django 3.0.6 on 2020-05-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecrime', '0010_addcriminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_title', models.CharField(max_length=50)),
                ('crime_date', models.DateField()),
                ('crime_description', models.TextField()),
                ('criminal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecrime.AddCriminal')),
            ],
        ),
    ]
